SELECT
  DATE_FORMAT(U.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
  U.PRODUCT_ID,
  U.USER_ID,
  U.SALES_AMOUNT
FROM (
    SELECT
      ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM ONLINE_SALE
    UNION ALL
    SELECT
      OFFLINE_SALE_ID, NULL AS USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM OFFLINE_SALE
  ) AS U
WHERE YEAR(U.SALES_DATE) = 2022 AND MONTH(U.SALES_DATE) = 3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID