SELECT
  DATE_FORMAT(S.SALES_DATE, '%Y') AS YEAR,
  DATE_FORMAT(S.SALES_DATE, '%m') AS MONTH,
  COUNT(DISTINCT(S.USER_ID)) AS PUCHASED_USERS,
  ROUND(COUNT(DISTINCT(S.USER_ID)) /
        (SELECT COUNT(DISTINCT(u.USER_ID))
         FROM USER_INFO AS U
         WHERE DATE_FORMAT(U.JOINED, '%Y') = 2021), 1)AS PUCHASED_RATIO
FROM ONLINE_SALE AS S
JOIN USER_INFO AS U
  ON S.USER_ID = U.USER_ID
WHERE DATE_FORMAT(U.JOINED, '%Y') = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH