SELECT
  BD.WRITER_ID,
  U.NICKNAME,
  SUM(BD.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS BD
JOIN USED_GOODS_USER AS U ON BD.WRITER_ID = U.USER_ID
WHERE BD.STATUS = 'DONE'
GROUP BY BD.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES