SELECT
  BOOK.CATEGORY, SUM(BOOK_SALES.SALES)
  FROM BOOK, BOOK_SALES
WHERE BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
  AND MONTH(BOOK_SALES.SALES_DATE) = 1 AND YEAR(BOOK_SALES.SALES_DATE) = 2022
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY